### ISSUE TITLE
Configuration site Lokisalle

### ISSUE THREAD

**Issue by turkish78320** [erwanthomas/lokisalle#1]
Bonjour,

J'ai bien reçu votre email et je vous remercie de votre réactivité, du coup je n’arrive toujours pas  à le mettre en ligne

**Comment by erwanthomas** [comment]
Bonjour,

Avez-vous vérifié les points suivants :

1. la configuration de la connexion à la BDD est correcte dans le fichier `core/config.php`.
2. le site est accessible via un nom d'hôte propre.
3. le serveur web est configuré pour servir les fichiers à partir du dossier `public`.
4. le serveur web est configuré pour réécrire l'URL des requêtes tel que donné en exemple dans le dossier `_metadata`.

Si tout est correct, pouvez-vous donner plus d'informations sur votre configuration et les bugs rencontrés ?

**Comment by turkish78320** [comment]
Bonjour,

Merci de votre réponse, je vais essayer de l'installer en local, je reviens vers vous si j'ai des problèmes

Merci beaucoup

**Comment by turkish78320** [comment]
Bonjour,

Que faut-il modifier dans le fichier htaccess?

**Comment by turkish78320** [comment]
Comment faire pour que le serveur web soit configuré pour servir les fichiers à partir du dossier public?

Merci d'avance

**Comment by erwanthomas** [comment]
Il existe différents serveurs web, chacun ayant son propre fonctionnement et ses propres manières de le configurer. Dans le dossier `_metadata` du projet, vous trouverez des exemples valides de configuration pour les deux serveurs web les plus connus, *Apache* et *nginx*. Ces configurations sont exclusives l'une de l'autre: par exemple, si vous utilisez *nginx*, le `.htaccess` ne sert à rien, car il s'agit d'un fichier de configuration propre à *Apache*. De même, *Apache* n'a aucune idée de ce que signifie la directive `root` d'un block `server` d'une configuration *nginx*.

Ignorant tout de l'environnement logiciel dans lequel vous tentez de faire tourner l'application, je ne peux donc pas répondre à vos questions, ni même garantir que les exemples de configuration de `_metadata` fonctionneront tels quels pour vous. Par ailleurs, il s'agit de questions qui ne concernent pas directement l'application et pour lesquelles vous trouverez des réponses dans la documentation des logiciels que vous utilisez, voire même sur des sites plus généralistes. Quoi qu'en il en soit, il me sera difficile de vous aider sur ces points.

Àfin de faciliter votre recherche, je vous recommande les tutoriels clairs de *DigitalOcean* sur l'administration serveur. Si vous utilisez un environnement *LAMP*, je vous recommande les deux suivants (sachez qu'il existe leurs équivalents pour *LEMP*):

1. https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-14-04
2. https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts (celui-ci répondra sans doute plus particulièrement à vos questions).
